parameters:
#    cnctuser.example.class: cnct\userBundle\Example

services:
#    cnctuser.example:
#        class: %cnctuser.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
